name = "catastrophic"
version = "1.0.0"
description = "SANS-IO Anthropic API client for Gleam"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
castor = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.5.3 and < 2.0.0"
pprint = ">= 1.0.6 and < 2.0.0"
